version: '3.8'

services:
  apiservice:
    image: ghcr.io/andrew-m-denooyer/sample-service:latest
    build:
      context: .
      dockerfile: AspireSample.ApiService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - aspire-net
    restart: unless-stopped

  webfrontend:
    image: ghcr.io/andrew-m-denooyer/sample-web:latest
    build:
      context: .
      dockerfile: AspireSample.Web/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiService__BaseUrl=http://apiservice:8080
    depends_on:
      - apiservice
    networks:
      - aspire-net
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
      - "9201:9201"
    mem_limit: 2g
    networks:
      - aspire-net
    restart: unless-stopped

networks:
  aspire-net:
    driver: bridge
